More working on AutoCombineDust
left off here>
{BEGIN}
wallet.cpp:2275:6: error: prototype for ‘bool CWallet::CreateTransaction(const std::vector<std::pair<CScript, long int> >&, CWalletTx&, CReserveKey&, int64_t&, std::__cxx11::string&, const CCoinControl*, AvailableCoinsType, bool, int64_t)’ does not match any in class ‘CWallet’
 bool CWallet::CreateTransaction(const vector<pair<CScript, int64_t> >& vecSend,
      ^~~~~~~
In file included from wallet.cpp:10:0:
wallet.h:295:10: error: candidates are: bool CWallet::CreateTransaction(CScript, const int64_t&, CWalletTx&, CReserveKey&, int64_t&, std::__cxx11::string&, const CCoinControl*, AvailableCoinsType, bool, int64_t)
     bool CreateTransaction(CScript scriptPubKey,
          ^~~~~~~~~~~~~~~~~
wallet.h:288:10: error:                 bool CWallet::CreateTransaction(CScript, int64_t, CWalletTx&, CReserveKey&, int64_t&, const CCoinControl*)
     bool CreateTransaction(CScript scriptPubKey,
          ^~~~~~~~~~~~~~~~~
wallet.h:280:10: error:                 bool CWallet::CreateTransaction(const std::vector<std::pair<CScript, long int> >&, CWalletTx&, CReserveKey&, int64_t&, std::__cxx11::string&, const CCoinControl*, AvailableCoinsType, bool)
     bool CreateTransaction(const std::vector<std::pair<CScript, int64_t> >& vecSend,
          ^~~~~~~~~~~~~~~~~
wallet.cpp: In member function ‘void CWallet::AutoCombineDust()’:
wallet.cpp:3765:115: error: no matching function for call to ‘CWallet::CreateTransaction(std::vector<std::pair<CScript, long int> >&, CWalletTx&, CReserveKey&, CAmount&, std::__cxx11::string&, CCoinControl*&, AvailableCoinsType, bool, int64_t)’
         if (!CreateTransaction(vecSend, wtx, keyChange, nFeeRet, strErr, coinControl, ALL_COINS, false, int64_t(0))) {
                                                                                                                   ^
In file included from wallet.cpp:10:0:
wallet.h:280:10: note: candidate: bool CWallet::CreateTransaction(const std::vector<std::pair<CScript, long int> >&, CWalletTx&, CReserveKey&, int64_t&, std::__cxx11::string&, const CCoinControl*, AvailableCoinsType, bool)
     bool CreateTransaction(const std::vector<std::pair<CScript, int64_t> >& vecSend,
          ^~~~~~~~~~~~~~~~~
wallet.h:280:10: note:   candidate expects 8 arguments, 9 provided
wallet.cpp:2424:6: note: candidate: bool CWallet::CreateTransaction(CScript, int64_t, CWalletTx&, CReserveKey&, int64_t&, const CCoinControl*)
 bool CWallet::CreateTransaction(CScript scriptPubKey,
      ^~~~~~~
wallet.cpp:2424:6: note:   candidate expects 6 arguments, 9 provided
In file included from wallet.cpp:10:0:
wallet.h:295:10: note: candidate: bool CWallet::CreateTransaction(CScript, const int64_t&, CWalletTx&, CReserveKey&, int64_t&, std::__cxx11::string&, const CCoinControl*, AvailableCoinsType, bool, int64_t)
     bool CreateTransaction(CScript scriptPubKey,
          ^~~~~~~~~~~~~~~~~
wallet.h:295:10: note:   no known conversion for argument 1 from ‘std::vector<std::pair<CScript, long int> >’ to ‘CScript’
g++ -c -O2  -rdynamic -std=c++11 -pthread -Wall -Wextra -Wno-ignored-qualifiers -Wformat -Wformat-security -Wno-unused-parameter  -DBOOST_SPIRIT_THREADSAFE -D__USE_MINGW_ANSI_STDIO -DBOOST_NO_CXX11_SCOPED_ENUMS -I/root/neutron/latests/src -I/root/neutron/latests/src/obj -DENABLE_WALLET -DUSE_UPNP=0 -I/root/neutron/latests/src/leveldb/include -I/root/neutron/latests/src/leveldb/helpers -I/root/neutron/latests/src/univalue/include -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/walletdb.d -o obj/walletdb.o walletdb.cpp
makefile.unix:213: recipe for target 'obj/wallet.o' failed

{END}